- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Copy Nginx configuration file
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: Restart nginx

- name: Start and enable Nginx
  systemd:
    name: nginx
    enabled: yes
    state: started
